FROM randomdude/gcc-cross-x86_64-elf

RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get install -y nasm
RUN apt-get install -y xorriso
RUN apt-get install -y grub-pc-bin
RUN apt-get install -y grub-common

VOLUME /root/env
WORKDIR /root/env

RUN apt install build-essential -y --no-install-recommends

# docker build buildenv -t tkern-builder
# docker run --rm -it -v %cd%:/root/env tkern-builder
# make build-x86_64
# qemu-system-x86_64 -cdrom dist/x86_64/kernel.iso